### ISSUE TITLE
Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by sercant** [instrumentisto/flex-sdk-docker-image#3]
Hello, when I try to run:
`docker run --rm -it -v $(pwd):/app instrumentisto/flex-sdk gradle compile`

I get;

> Execution failed for task ':compileFlex'. 
>java.lang.Exception: mxmlc execution failed: Loading configuration file /flex-sdk/frameworks/flex-config.xmlError: Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.

running `docker run --rm -it -v $(pwd):/app instrumentisto/flex-sdk xvfb gradle compile`

fixes the issue.

**Comment by tyranron** [comment]
@s3rcan yeap. The image is not intended to run `xvfb` under-the-hood every time, because it's not required for every task, just for few of them. That's why you should specify `xvfb` explicitly in you command, if you need one. That is described in ["How to use this image" section of README](https://github.com/instrumentisto/flex-sdk-docker-image/tree/d1f3d8b9a1574517cd72713e0307d8a5302bf5fd#how-to-use-this-image).

**Comment by sercant** [comment]
I wasn't running any test, I was only trying to build the project but without `xvfb` it wasn't letting me compile.

**Comment by tyranron** [comment]
@s3rcan so I can suggest your build scenario requires `xvfb` somehow.
